### ISSUE TITLE
Download URL is None on a very specfic mod

### ISSUE THREAD

**Issue by Advik-B** [Owen-Cochell/cursepy#13]
```python
from cursepy import CurseClient
from v import api_key

c = CurseClient(api_key)
game = c.game(432) # Minecraft
addon = c.addon(400012) # Ex Nihilo: Sequentia

for file in addon.files():  # type: ignore
    print(file.download_url)

```
<img width="190" alt="Screenshot 2022-11-23 at 9 25 55 PM" src="https://user-images.githubusercontent.com/86160411/203591476-86167906-8b23-4a5a-93a9-9d7eed2a778b.png">

**Comment by OwenCochell** [comment]
Hey, thank you for reporting this issue!

This is a tricky problem. After messing around a bit, it appears the Curse Forge is serving 'None' for for the download URL. I suspect this is because the mod has not been approved for distribution outside of the official curseforge ecosystem. The mode developer can choose weather their mod is approved on the 'creator dashboard', so maybe the mod you ran into has this disabled. You can read about this [here](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3). I couldn't find anything in the official documentation, and I don't have access to any 'creator dashboard', but i'm pretty sure this is the issue.

However, there may be a solution. I believe we can create a download link using the information provided. I'll play around with my idea and see how it works large scale. If I get something workable i'll post my methods here, and update the library with this fix. Hopefully I can get this out today or tomorrow.

Thanks!

**Comment by OwenCochell** [comment]
In the latest cursepy version, 2.2.0, the `CurseFile` class can now generate a guess download URL using the `guess_download()` method. From my testing, this URL seems to work fine, and can download the associated files. This creates a URL to the CurseForge CDN, which is likely what most people want. You can read up on the [updated documentation](https://cursepy.readthedocs.io/en/latest/basic/curse_inst.html#cursefile) for more info on this method and how to use it.

Again, this feature has not been tested very well! The addition works for the addon you specified, but it is unknown weather it will work for other addons. Please let me know if you run into any issues with this, so we can fine tune this feature.

Thanks again for reporting this! If this does not work then please let me know, otherwise we can close this issue.
